import React from 'react'
import { Metadata } from 'next'
export const metadata: Metadata = {
  title:  "Flipini: l'appli pour consulter Catalogues et Promos de vos enseignes préférées.",
  description:
    "Flipini est une application innovante qui vous permet de consulter les catalogues en ligne des enseignes françaises spécialisées dans la grande distribution, l'électroménager, le bricolage, la mode et bien d'autres domaines. L'application met à votre disposition une vaste sélection de catalogues pour vous aider à dénicher les meilleures offres et promotions en un seul endroit.",
}
export default function PrivacyPolice() {
    return (
        <div className="container" style={{paddingTop: "6rem"}}>
            <p className="p1"><span className="s1"><strong>Privacy Policy</strong></span></p>
            <p className="p2"><span className="s1">Last updated: August 31, 2021</span></p>
            <p className="p2"><span className="s1">This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</span></p>
            <p className="p2"><span className="s1">We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.<span className="Apple-converted-space">&nbsp;</span></span></p>
            <p className="p1"><span className="s1"><strong>Interpretation and Definitions</strong></span></p>
            <p className="p3"><span className="s1"><strong>Interpretation</strong></span></p>
            <p className="p2"><span className="s1">The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</span></p>
            <p className="p3"><span className="s1"><strong>Definitions</strong></span></p>
            <p className="p2"><span className="s1">For the purposes of this Privacy Policy:</span></p>
            <ul className="ul1">
            <li className="li4"><span className="s3"><strong>Account</strong>&nbsp;means a unique account created for You to access our Service or parts of our Service.</span></li>
            <li className="li4"><span className="s3"><strong>Affiliate</strong>&nbsp;means an entity that controls, is controlled by or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</span></li>
            <li className="li4"><span className="s3"><strong>Application</strong>&nbsp;means the software program provided by the Company downloaded by You on any electronic device, named flipini.fr</span></li>
            <li className="li4"><span className="s3"><strong>Company</strong>&nbsp;(referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to flipini.fr, 24-34 rue princesse lalla A&iuml;cha</span><span className="s4">،</span><span className="s3"> 14000 K&eacute;nitra, Maroc.</span></li>
            <li className="li4"><span className="s3"><strong>Country</strong>&nbsp;refers to: Morocco</span></li>
            <li className="li4"><span className="s3"><strong>Device</strong>&nbsp;means any device that can access the Service such as a cellphone or a digital tablet.</span></li>
            <li className="li4"><span className="s3"><strong>Personal Data</strong>&nbsp;is any information that relates to an identified or identifiable individual.</span></li>
            <li className="li4"><span className="s3"><strong>Service</strong>&nbsp;refers to the Application.</span></li>
            <li className="li4"><span className="s3"><strong>Service Provider</strong>&nbsp;means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</span></li>
            <li className="li4"><span className="s3"><strong>Usage Data</strong>&nbsp;refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</span></li>
            <li className="li4"><span className="s3"><strong>You</strong>&nbsp;means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</span></li>
            </ul>
            <p className="p1"><span className="s1"><strong>Collecting and Using Your Personal Data</strong></span></p>
            <p className="p3"><span className="s1"><strong>Types of Data Collected</strong></span></p>
            <p className="p5"><span className="s1"><strong>Personal Data</strong></span></p>
            <p className="p2"><span className="s1">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</span></p>
            <ul className="ul1">
            <li className="li4"><span className="s3">Email address</span></li>
            <li className="li4"><span className="s3">First name and last name</span></li>
            <li className="li4"><span className="s3">Phone number</span></li>
            <li className="li4"><span className="s3">Address, State, Province, ZIP/Postal code, City</span></li>
            <li className="li4"><span className="s3">Usage Data</span></li>
            </ul>
            <p className="p5"><span className="s1"><strong>Usage Data</strong></span></p>
            <p className="p2"><span className="s1">Usage Data is collected automatically when using the Service.</span></p>
            <p className="p2"><span className="s1">Usage Data may include information such as Your Device&quot;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</span></p>
            <p className="p2"><span className="s1">When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</span></p>
            <p className="p2"><span className="s1">We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</span></p>
            <p className="p5"><span className="s1"><strong>Information Collected while Using the Application</strong></span></p>
            <p className="p2"><span className="s1">While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:</span></p>
            <ul className="ul1">
            <li className="li4"><span className="s3">Information regarding your location</span></li>
            <li className="li4"><span className="s3">Pictures and other information from your Device&apos;s camera and photo library</span></li>
            </ul>
            <p className="p2"><span className="s1">We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company&apos;s servers and/or a Service Provider&apos;s server or it may be simply stored on Your device.</span></p>
            <p className="p2"><span className="s1">You can enable or disable access to this information at any time, through Your Device settings.</span></p>
            <p className="p3"><span className="s1"><strong>Use of Your Personal Data</strong></span></p>
            <p className="p2"><span className="s1">The Company may use Personal Data for the following purposes:</span></p>
            <ul className="ul1">
            <li className="li4"><span className="s3"><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</span></li>
            <li className="li4"><span className="s3"><strong>To manage Your Account:</strong>&nbsp;to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</span></li>
            <li className="li4"><span className="s3"><strong>For the performance of a contract:</strong>&nbsp;the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</span></li>
            <li className="li4"><span className="s3"><strong>To contact You:</strong>&nbsp;To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application&apos;s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</span></li>
            <li className="li4"><span className="s3"><strong>To provide You</strong>&nbsp;with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</span></li>
            <li className="li4"><span className="s3"><strong>To manage Your requests:</strong>&nbsp;To attend and manage Your requests to Us.</span></li>
            <li className="li4"><span className="s3"><strong>For business transfers:</strong>&nbsp;We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</span></li>
            <li className="li4"><span className="s3"><strong>For other purposes</strong>: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</span></li>
            </ul>
            <p className="p2"><span className="s1">We may share Your personal information in the following situations:</span></p>
            <ul className="ul1">
            <li className="li4"><span className="s3"><strong>With Service Providers:</strong>&nbsp;We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.</span></li>
            <li className="li4"><span className="s3"><strong>For business transfers:</strong>&nbsp;We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</span></li>
            <li className="li4"><span className="s3"><strong>With Affiliates:</strong>&nbsp;We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</span></li>
            <li className="li4"><span className="s3"><strong>With Your consent</strong>: We may disclose Your personal information for any other purpose with Your consent.</span></li>
            </ul>
            <p className="p3"><span className="s1"><strong>Retention of Your Personal Data</strong></span></p>
            <p className="p2"><span className="s1">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</span></p>
            <p className="p2"><span className="s1">The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</span></p>
            <p className="p3"><span className="s1"><strong>Transfer of Your Personal Data</strong></span></p>
            <p className="p2"><span className="s1">Your information, including Personal Data, is processed at the Company&quot;s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to &mdash; and maintained on &mdash; computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</span></p>
            <p className="p2"><span className="s1">Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</span></p>
            <p className="p2"><span className="s1">The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</span></p>
            <p className="p3"><span className="s1"><strong>Disclosure of Your Personal Data</strong></span></p>
            <p className="p5"><span className="s1"><strong>Business Transactions</strong></span></p>
            <p className="p2"><span className="s1">If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</span></p>
            <p className="p5"><span className="s1"><strong>Law enforcement</strong></span></p>
            <p className="p2"><span className="s1">Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</span></p>
            <p className="p5"><span className="s1"><strong>Other legal requirements</strong></span></p>
            <p className="p2"><span className="s1">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</span></p>
            <ul className="ul1">
            <li className="li4"><span className="s3">Comply with a legal obligation</span></li>
            <li className="li4"><span className="s3">Protect and defend the rights or property of the Company</span></li>
            <li className="li4"><span className="s3">Prevent or investigate possible wrongdoing in connection with the Service</span></li>
            <li className="li4"><span className="s3">Protect the personal safety of Users of the Service or the public</span></li>
            <li className="li4"><span className="s3">Protect against legal liability</span></li>
            </ul>
            <p className="p3"><span className="s1"><strong>Security of Your Personal Data</strong></span></p>
            <p className="p2"><span className="s1">The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</span></p>
            <p className="p1"><span className="s1"><strong>Children&quot;s Privacy</strong></span></p>
            <p className="p2"><span className="s1">Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</span></p>
            <p className="p2"><span className="s1">If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent&quot;s consent before We collect and use that information.</span></p>
            <p className="p1"><span className="s1"><strong>Links to Other Websites</strong></span></p>
            <p className="p2"><span className="s1">Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party&quot;s site. We strongly advise You to review the Privacy Policy of every site You visit.</span></p>
            <p className="p2"><span className="s1">We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</span></p>
            <p className="p1"><span className="s1"><strong>Changes to this Privacy Policy</strong></span></p>
            <p className="p2"><span className="s1">We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</span></p>
            <p className="p2"><span className="s1">We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.</span></p>
            <p className="p2"><span className="s1">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</span></p>
            <p className="p1"><span className="s1"><strong>Contact Us</strong></span></p>
            <p className="p2"><span className="s1">If you have any questions about this Privacy Policy, You can contact us:</span></p>
            <ul className="ul1">
            <li className="li4"><span className="s3">By email: contact@flipini.fr</span></li>
            </ul>
            <p className="p6">&nbsp;</p>
            <p className="p1"><span className="s1"><strong>Terms &amp; Conditions</strong></span></p>
            <p className="p7"><span className="s1">By downloading or using the app, these terms will automatically apply to you &ndash; you should make sure therefore that you read them carefully before using the app. You&rsquo;re not allowed to copy, or modify the app, any part of the app, or our trademarks in any way. You&rsquo;re not allowed to attempt to extract the source code of the app, and you also shouldn&rsquo;t try to translate the app into other languages, or make derivative versions. The app itself, and all the trade marks, copyright, database rights and other intellectual property rights related to it, still belong to flipini.fr.</span></p>
            <p className="p8">&nbsp;</p>
            <p className="p7"><span className="s1">flipini.fr is committed to ensuring that the app is as useful and efficient as possible. For that reason, we reserve the right to make changes to the app or to charge for its services, at any time and for any reason. We will never charge you for the app or its services without making it very clear to you exactly what you&rsquo;re paying for.</span></p>
            <p className="p8">&nbsp;</p>
            <p className="p7"><span className="s1">The flipini.fr app stores and processes personal data that you have provided to us, in order to provide our Service. It&rsquo;s your responsibility to keep your phone and access to the app secure. We therefore recommend that you do not jailbreak or root your phone, which is the process of removing software restrictions and limitations imposed by the official operating system of your device. It could make your phone vulnerable to malware/viruses/malicious programs, compromise your phone&rsquo;s security features and it could mean that the flipini.fr app won&rsquo;t work properly or at all.</span></p>
            <p className="p8">&nbsp;</p>
            <p className="p7"><span className="s1">You should be aware that there are certain things that flipini.fr will not take responsibility for. Certain functions of the app will require the app to have an active internet connection. The connection can be Wi-Fi, or provided by your mobile network provider, but flipini.fr cannot take responsibility for the app not working at full functionality if you don&rsquo;t have access to Wi-Fi, and you don&rsquo;t have any of your data allowance left.</span></p>
            <p className="p7"><span className="s1">If you&rsquo;re using the app outside of an area with Wi-Fi, you should remember that your terms of the agreement with your mobile network provider will still apply. As a result, you may be charged by your mobile provider for the cost of data for the duration of the connection while accessing the app, or other third party charges. In using the app, you&rsquo;re accepting responsibility for any such charges, including roaming data charges if you use the app outside of your home territory (i.e. region or country) without turning off data roaming. If you are not the bill payer for the device on which you&rsquo;re using the app, please be aware that we assume that you have received permission from the bill payer for using the app.</span></p>
            <p className="p8">&nbsp;</p>
            <p className="p7"><span className="s1">Along the same lines, flipini.fr cannot always take responsibility for the way you use the app i.e. You need to make sure that your device stays charged &ndash; if it runs out of battery and you can&rsquo;t turn it on to avail the Service, flipini.fr cannot accept responsibility.</span></p>
            <p className="p8">&nbsp;</p>
            <p className="p7"><span className="s1">With respect to flipini.fr &rsquo;s responsibility for your use of the app, when you&rsquo;re using the app, it&rsquo;s important to bear in mind that although we endeavor to ensure that it is updated and correct at all times, we do rely on third parties to provide information to us so that we can make it available to you. flipini.fr accepts no liability for any loss, direct or indirect, you experience as a result of relying wholly on this functionality of the app.</span></p>
            <p className="p8">&nbsp;</p>
            <p className="p7"><span className="s1">At some point, we may wish to update the app. The app is currently available on Android &ndash; the requirements for system (and for any additional systems we decide to extend the availability of the app to) may change, and you&rsquo;ll need to download the updates if you want to keep using the app. flipini.fr does not promise that it will always update the app so that it is relevant to you and/or works with the Android version that you have installed on your device. However, you promise to always accept updates to the application when offered to you, We may also wish to stop providing the app, and may terminate use of it at any time without giving notice of termination to you. Unless we tell you otherwise, upon any termination, (a) the rights and licenses granted to you in these terms will end; (b) you must stop using the app, and (if needed) delete it from your device.</span></p>
            <p className="p9">&nbsp;</p>
            <p className="p10"><span className="s1"><strong>Changes to This Terms and Conditions</strong></span></p>
            <p className="p11">&nbsp;</p>
            <p className="p7"><span className="s1">We may update our Terms and Conditions from time to time. Thus, you are advised to review this page periodically for any changes. We will notify you of any changes by posting the new Terms and Conditions on this page.</span></p>
            <p className="p7"><span className="s1">These terms and conditions are effective as of 2021-05-31</span></p>
            <p className="p9">&nbsp;</p>
            <p className="p10"><span className="s1"><strong>Contact Us</strong></span></p>
            <p className="p11">&nbsp;</p>
            <p className="p7"><span className="s1">If you have any questions or suggestions about our Terms and Conditions, do not hesitate to contact us at contact@flipini.fr.</span></p>
            <p className="p6">&nbsp;</p>
        </div>
    )
}
